In [1]:
import os
from glob import glob
import numpy as np
import json

import cv2
from tqdm.notebook import tqdm

import ffmpeg_utils
from augment_script import process_video, process_images
from augment import Augmentations
from reader import VideoEffectReader, ImageEffectReader
from writer import COCO_writer
from bbox_utils import get_scale_ratio, resize_by_max_side

### Preprocess effects

In [2]:
e_type = 'fire'
e_type = 'smoke'
e_type = 'real_fire_smoke'

def get_effect_paths(e_type):
    assert e_type in ['fire', 'smoke', 'real_fire_smoke'], 'Unsupported'
    raw_png_effects_path  = f'effects/raw_{e_type}_images'
    prep_png_effects_path = f'effects/prep_{e_type}_images'
    raw_mov_effects_path  = f'effects/raw_{e_type}_vid'
    prep_mov_effects_path = f'effects/prep_{e_type}_vid'
    return (raw_png_effects_path, prep_png_effects_path,
            raw_mov_effects_path, prep_mov_effects_path)

(raw_png_effects_path, prep_png_effects_path,
 raw_mov_effects_path, prep_mov_effects_path) = get_effect_paths(e_type)


vid_out_path = 'output/out.mp4'
annot_out_path = 'output/annotations/instances_default.json'

# Create folders
for path in [raw_png_effects_path, prep_png_effects_path,
             raw_mov_effects_path, prep_mov_effects_path,
             os.path.split(vid_out_path)[0],
             os.path.split(annot_out_path)[0]]:
    os.makedirs(path, exist_ok=True)

In [3]:
# Rename and trim empty pixels
raw_png_effects_path = 'effects/non_funny'
prep_png_effects_path = 'effects/prep_non_funny'
e_type = 'non-funny'
# for i, effect_path in enumerate(glob(os.path.join(raw_png_effects_path, '*.png'))):
#     e_img = cv2.imread(effect_path, cv2.IMREAD_UNCHANGED)
#     # Trim empty pixels
#     y, x = e_img[:, :, 3].nonzero()
#     minx, miny = np.min(x), np.min(y)
#     maxx, maxy = np.max(x), np.max(y)
#     e_img = e_img[miny:maxy, minx:maxx]
#     # Resize to 512px
#     scale_ratio = get_scale_ratio(e_img, 512)
#     e_img = resize_by_max_side(e_img, scale_ratio)
#     os.makedirs(prep_png_effects_path, exist_ok=True)
#     cv2.imwrite(os.path.join(prep_png_effects_path, f'{e_type}-{i}.png'), e_img)

In [4]:
# Rename videos
# for i, mov_path in enumerate(glob(os.path.join(raw_mov_effects_path, '*.mov'))):
#     print(mov_path)
#     path = os.path.split(mov_path)[0]
#     os.rename(mov_path, os.path.join(path, f'{e_type}-{i}.mov'))

In [5]:
# Resize and extract alpha videos
rewrite = False
# for input_path in glob(os.path.join(raw_mov_effects_path, '*.mov')):
#     input_path = os.path.abspath(input_path)
#     filename = os.path.splitext(os.path.split(input_path)[1])[0]
#     out_path = os.path.join(prep_mov_effects_path, filename + '.webm')
#     out_path = os.path.abspath(out_path)
#     ffmpeg_utils.convert_mov2webm(input_path, out_path, y=rewrite)
#     ffmpeg_utils.extract_alpha(out_path, y=rewrite)

In [6]:
# e_paths = get_effect_paths('fire')
e_paths = get_effect_paths('real_fire_smoke')
prep_e_png_fire_path, prep_e_mov_fire_path = e_paths[1], e_paths[3]
e_paths = get_effect_paths('smoke')
prep_e_png_smoke_path, prep_e_mov_smoke_path = e_paths[1], e_paths[3]

In [7]:
e_png_fire = glob(os.path.join(prep_e_png_fire_path, '*.png'))
e_png_fire = glob(os.path.join('effects/animals/retrieved', '*.png'))
e_mov_fire = glob(os.path.join(prep_e_mov_fire_path, '*.webm'))
e_png_smoke = glob(os.path.join(prep_e_png_smoke_path, '*.png'))
e_mov_smoke = glob(os.path.join(prep_e_mov_smoke_path, '*.webm'))
e_png_fire[:15], e_mov_fire[:15], e_png_smoke[:15], e_mov_smoke[:15]

(['effects/animals/retrieved\\0000001.png',
  'effects/animals/retrieved\\0000002.png',
  'effects/animals/retrieved\\0000003.png',
  'effects/animals/retrieved\\0000004.png',
  'effects/animals/retrieved\\0000005.png',
  'effects/animals/retrieved\\0000006.png',
  'effects/animals/retrieved\\0000007.png',
  'effects/animals/retrieved\\0000008.png',
  'effects/animals/retrieved\\0000009.png',
  'effects/animals/retrieved\\0000010.png',
  'effects/animals/retrieved\\0000011.png',
  'effects/animals/retrieved\\0000012.png',
  'effects/animals/retrieved\\0000013.png',
  'effects/animals/retrieved\\0000014.png',
  'effects/animals/retrieved\\0000015.png'],
 ['effects/prep_real_fire_smoke_vid\\fire-1.webm',
  'effects/prep_real_fire_smoke_vid\\fire-2.webm',
  'effects/prep_real_fire_smoke_vid\\fire-3.webm',
  'effects/prep_real_fire_smoke_vid\\smoke-1.webm',
  'effects/prep_real_fire_smoke_vid\\smoke-2.webm'],
 ['effects/prep_smoke_images\\smoke-0.png',
  'effects/prep_smoke_images\\smoke-1

### Augment

In [8]:
source_videos = glob('source_videos/*')
source_videos

['source_videos\\2020-06-23_16-40-40.mp4',
 'source_videos\\stream_OV1_2020-08-01_09_58_11.ts.mp4',
 'source_videos\\stream_OV1_2020-08-01_09_58_50.ts.mp4']

In [15]:
# COCO_writer
coco_writer = COCO_writer([
    {
        'name': 'Fire',
        'supercategory': '',
        'id': 2,
    },
    {
        'name': 'Smoke',
        'supercategory': '',
        'id': 4,
    },
])

e_readers = [
#     VideoEffectReader(e_mov_fire[1:2]),
    ImageEffectReader(e_png_fire, annot_type='coco', preload=False),
]


# Augmentations
fire_augment = Augmentations(
    e_readers,
    config_path='augment_config.yaml',
    mov_min_size= 300,
    mov_max_size= 900,
    do_resize=True,
    do_flip=True,
    do_rotate=True,
    do_brightness=True,
    do_gamma=True,
    do_blur=True,
    blur_radius=11,
    contour_radius=10,
    debug_level=2,
    min_n_objects=10,
    max_n_objects=10,
    use_alpha=True,
    min_transparency=100,
    max_transparency=100,
    ck_start=1,
    ck_range=10,
    min_duration=1,
    max_duration=2,
)

# smoke_augment = Augmentations(
#     e_png_smoke,
#     e_mov_smoke,
#     config_path='augment_config.yaml',
#     do_resize=True,
#     do_flip=True,
#     do_rotate=False,
#     do_contrast=False,
#     debug_level=2,
#     ck_start=2,
#     ck_range=15,
#     max_n_objects=3,
#     use_alpha=True
# )

augmentations = [
    fire_augment,
#     smoke_augment
]

# process_video(source_videos[0], augmentations, vid_out_path, coco_writer, show_debug=True)

# # Write annotations.
# os.makedirs(os.path.split(annot_out_path)[0], exist_ok=True)
# coco_writer.write_result(annot_out_path)

loading annotations into memory...
Done (t=9.64s)
creating index...
index created!


In [10]:
e_readers[0].loaded[:15]

['effects/animals/retrieved\\0000001.png',
 'effects/animals/retrieved\\0000002.png',
 'effects/animals/retrieved\\0000003.png',
 'effects/animals/retrieved\\0000004.png',
 'effects/animals/retrieved\\0000005.png',
 'effects/animals/retrieved\\0000006.png',
 'effects/animals/retrieved\\0000007.png',
 'effects/animals/retrieved\\0000008.png',
 'effects/animals/retrieved\\0000009.png',
 'effects/animals/retrieved\\0000010.png',
 'effects/animals/retrieved\\0000011.png',
 'effects/animals/retrieved\\0000012.png',
 'effects/animals/retrieved\\0000013.png',
 'effects/animals/retrieved\\0000014.png',
 'effects/animals/retrieved\\0000015.png']

In [16]:
process_video(source_videos[0], augmentations, vid_out_path, coco_writer, show_debug=True, write_debug=False)

  1%|▉                                                                           | 184/15004 [01:36<2:09:26,  1.91it/s]


In [24]:
# Fix for `id=0` for all annotations
# for path in glob('effects/prep_real_fire_smoke_vid/annotations/fire-3.json'):
#     with open(path) as in_file:
#         j = json.load(in_file)
#     for i, annot in enumerate(j['annotations']):
#         annot['id'] = i
#         j['annotations'][i] = annot
    
#     with open(path, 'w') as out_file:
#         out_file.write(json.dumps(j))

In [175]:
def rotate_poly(poly, angle, cx, cy, h, w):
    """Rotate the polygon."""
    poly = poly.reshape(-1, 2)
    poly = np.hstack(
        (poly, np.ones((poly.shape[0], 1), dtype=poly[0][0].dtype)))

    M = cv2.getRotationMatrix2D((cx, cy), angle, 1.0)

    cos = np.abs(M[0, 0])
    sin = np.abs(M[0, 1])

    nW = int((h * sin) + (w * cos))
    nH = int((h * cos) + (w * sin))
    # adjust the rotation matrix to take into account translation
    M[0, 2] += (nW / 2) - cx
    M[1, 2] += (nH / 2) - cy
    # Prepare the vector to be transformed
    calculated = np.dot(M, poly.T).T
    return calculated#.reshape(-1, 1, 2)

In [176]:
corners = np.zeros((8))
corners = corners.reshape(-1, 2)
corners = np.hstack(
    (corners, np.ones((corners.shape[0], 1), dtype=type(corners[0][0]))))
corners.shape
corners

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [177]:
from bbox_utils import convert_xywh_xyxy, convert_xyxy_xywh, blur_contour, rotate_im

def rotate(image, angle, bboxes=None, segments=None):
    h, w = image.shape[:2]
    cx, cy = w // 2, h // 2

    # Rotate image.
    image = rotate_im(image, angle)

    # Scale back
    scale_factor_x = image.shape[1] / w
    scale_factor_y = image.shape[0] / h

    image = cv2.resize(image, (w, h))
    
    enclosing_polygons = None
    if segments is not None:
        M = cv2.getRotationMatrix2D((cx, cy), angle, 1.0)
        enclosing_polygons = []
        for segment in segments:
            seg = rotate_poly(segment, angle, cx, cy, h, w)
            seg = seg / [scale_factor_x, scale_factor_y]
            enclosing_polygons.append(seg)
        enclosing_polygons = np.array(enclosing_polygons).astype(np.int32)
        segments = enclosing_polygons
    elif bboxes is not None:
        corners = get_corners(bboxes)
        # Rotate corners.
        enclosing_polygons = rotate_box(corners, angle, cx, cy, h, w)
    if enclosing_polygons is not None:
        # Calculate enclosing bbox.
        bboxes = []
        for poly in enclosing_polygons:
            bbox = cv2.boundingRect(poly)
            bbox = convert_xywh_xyxy(bbox, w, h)
            bboxes.append(bbox)
        bboxes = np.array(bboxes, dtype=np.float32)
#         Scale back.
        bboxes[:, :4] /= [scale_factor_x, scale_factor_y] * 2

    return image, bboxes, segments

In [178]:

from pycocotools.coco import COCO
# animals_coco = COCO('effects/animals/animals.json')
# writer = COCO_writer(animals_coco.dataset['categories'])

In [182]:
from bbox_utils import convert_xywh_xyxy, convert_xyxy_xywh, blur_contour, rotate_im


pbar = tqdm(total=len(animals_coco.imgs))
for img_id, img_info in animals_coco.imgs.items():
    read_img_name = os.path.split(img_info['image'])[1]
    path = 'effects/animals/animals/' + read_img_name
    image = cv2.imread(path)
    ann_ids = animals_coco.getAnnIds(imgIds=img_id, iscrowd=None)
    for obj in animals_coco.loadAnns(ann_ids):
        if obj['area'] < 3000:
            continue
        mask = np.zeros((*image.shape[:2], 1), dtype=np.uint8)
        segments = []
        for segment in obj['segmentation'][:1]:
            segment = np.array(segment).reshape(-1, 1, 2).astype(np.int32)
            segments.append(segment)
        segments = np.array(segments).reshape(-1, 1, 2)
        cv2.fillPoly(mask, [segments], (255))
        img = image.copy()
        img = np.concatenate((img, mask), -1)
        img = blur_contour(img, blur_radius=21, contour_radius=15, blur_image=False)
        
        y, x = img[:, :, 3].nonzero()
        minx, miny = np.min(x), np.min(y)
        maxx, maxy = np.max(x), np.max(y)
        img = img[miny:maxy, minx:maxx]
        
        
        segmentations = []
        for segment in segments:
            seg = np.array(segment).reshape(-1, 1, 2) - (minx, miny)
            h, w = img.shape[:2]
            seg[:, :, 0] = np.clip(seg[:, :, 0], 0, w - 1)
            seg[:, :, 1] = np.clip(seg[:, :, 1], 0, h - 1)
            segmentations.append(seg)
        segments = segmentations
        
        img, _, segments = rotate(img, angle=15, segments=segments)
        img, mask = img[:, :, :3].copy(), img[:, :, 3:].copy()
        
        bbox = cv2.boundingRect(segments)
        bbox = convert_xywh_xyxy(bbox, *img.shape[:2][::-1])
        print(bbox)
        cv2.rectangle(img, tuple(bbox[:2]), tuple(bbox[2:4]), (22, 48, 163), 2)
        for segment in segments:
            cv2.drawContours(img, segments, -1, (0, 0, 255), 4)
        cv2.imshow('orig_image', image)
        cv2.imshow('img_orig', img)
        cv2.imshow('img', (img * (mask / 255)).astype(np.uint8))
        cv2.imshow('mask', mask)
        key = cv2.waitKey(0) & 0xFF
        if key == ord('q'):
            break
    if key == ord('q'):
            break
    pbar.update(1)
cv2.destroyAllWindows()
# writer.write_result('effects/animals/retrieved.json')

[ 41  20 184 169]
[  2  12 543 279]
[ 49  21 198 315]
[ 32  36 576 229]
[ 60  28 346 390]
[ 49  33 306 269]
[ 19  37 211 252]
[ 57  48 410 404]
[ 22  55 492 180]


In [173]:
effect_path = 'effects/prep_real_fire_smoke_vid/fire-3'
cap = cv2.VideoCapture(f'{effect_path}.webm')
alpha_cap = cv2.VideoCapture(f'{effect_path}_alpha.mp4')
while True:
    ret, e_frame = cap.read()
    a_ret, e_alpha = alpha_cap.read()
    init_e_alpha = e_alpha.copy()
    if not ret or not a_ret:
        print(ret, a_ret)
        break
#     rgb_sum = np.expand_dims(np.sum(e_alpha, axis=2), -1)
#     e_alpha = np.clip(rgb_sum, 0, 255, dtype=np.uint8)
    e_alpha = e_alpha[:, :, :1]
    print(e_alpha.shape)
    e_mask = np.ones(e_alpha.shape, dtype=np.uint8) * 255
    e_frame = np.concatenate((e_frame, e_alpha), axis=2)
    # Blur
    blur_radius = 21
    contour_radius = 5
    
    
    image, alpha = e_frame[:, :, :3], e_frame[:, :, 3:].copy()

    contours, _ = cv2.findContours(alpha.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    print(contours[0].shape, contours[0].dtype)
    cv2.boundingRect(contours[0])
    
    b_rad = (blur_radius, blur_radius)
    blurred_img = image#cv2.GaussianBlur(image, b_rad, 0)
    alpha[:, :, 0] = cv2.GaussianBlur(alpha, b_rad, 0)

    mask = np.zeros((*image.shape[:2], 1), np.ubyte)
    cv2.drawContours(mask, contours, -1, (1), contour_radius)
    output = np.where(mask, blurred_img, image)
    print((alpha / 255).max(), np.median(alpha / 255))
    print(output.max())
    output[...] = output * (alpha / 255)
    print(output.max())
    cv2.imshow('alpha', init_e_alpha)
    cv2.imshow('mask', mask * 255)
    cv2.imshow('output', output)
    cv2.imshow('e_frame', e_frame)
    
    cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 720, 1)
(6, 1, 2) int32
0.9921568627450981 0.0
255
253
(500, 720, 1)
(10, 1, 2) int32
0.9921568627450981 0.0
255
253
(500, 720, 1)
(10, 1, 2) int32
0.9921568627450981 0.0
255
253


KeyboardInterrupt: 

In [ ]:
%load_ext line_profiler
%load_ext memory_profiler

In [ ]:
from augment import Augmentations
from augment_script import _process_image
from bbox_utils import (convert_xywh_xyxy, convert_xyxy_xywh,
                        resize, rotate, flip, gamma_correction,
                        blur_contour)

augment = Augmentations.augment
merge_images = Augmentations.merge_images

In [ ]:
%lprun -f blur_contour process_video(source_videos[0], augmentations, vid_out_path, coco_writer, show_debug=False)

In [ ]:
images = glob(os.path.join('ufa/images', f'*.jpg'))
out_path = 'output/test'
show_debug, write_debug = False, False
%lprun -f process_images process_images(images, augmentations, out_path, coco_writer, show_debug, write_debug, n_workers=None)

In [44]:
a = np.random.normal(loc=0.8, scale=0.05, size=10000)
b = np.random.normal(loc=0, scale=2.5, size=10000)
print(a.min(), a.max(), a.mean())
print(b.min(), b.max(), b.mean())

0.5922650026558175 0.9899783176964153 0.8003302973044949
-9.670270866233837 8.323729912185293 -0.022608726770813894


In [ ]:
images = glob('effects/prep_non_funny/*.png')
images = glob(os.path.join('ufa/images', f'*.jpg'))

In [45]:
np.clip([0, 2, 3], 1, 2)

array([1, 2, 2])

In [32]:
cv2.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture('effects/prep_real_fire_smoke_vid/smoke-2.webm')
cur_pos = cap.get(cv2.CAP_PROP_POS_FRAMES)
print(cur_pos)
cap.read()
print(cap.get(cv2.CAP_PROP_POS_FRAMES))

#### TODO


##### General
* <s>move everything to config file</s>
* написать loop чтобы обработать все видосы

##### Preparation
* <s>remove clear pixels</s>
* remove clear pixels from video

##### Augmentation
* <s>cover all image</s>
* <s>change sizes</s>
* <s>flip</s>
* <s>add animations</s>
* <s>proper resizing</s>
* <s>make an offset point a down center point of the effect image.</s>
* <s>fix merging with video - fix: Color keying</s>
* <s>поиграться с color keying'ом, чтобы более плавные переходы в нём были</s>
* <s>change angle</s>
* <s>contrast and brightness</s>
* <s>gamma correction</s>
* <s>find new effects, add smoke</s>
* warp perspective

##### Annotation
* <s>add dynamic bboxes for videos</s>
* <s>fix bboxes for some videos</s>
* <s>annotate all videos</s>
* <s>annotation for images</s>
* <s>scaling bboxes</s>
* <s>rotating bboxes</s>
* <s>Write to COCO</s>
* <s>Get class from annotation, not by fixing it for Augmentation object</s>
* разметить эффекты не боксом, а полигоном, чтобы можно было нормально поворачивать эффект и при этом иметь нормальный бокс



## Working with videos

#### Scale down with keeping alpha channel
```shell
ffmpeg -i in.mov -filter:v scale=720:-1 -c:v qtrle out.mov
```

#### `.mov` to `.webm` keeping  alpha channel

```shell
ffmpeg -i in.mov -c:v libvpx -pix_fmt yuva420p -auto-alt-ref 0 out.webm
```

#### Extract alpha channel from `.webm`

```shell
ffmpeg -vcodec libvpx -i in.webm -vf alphaextract -y out.mp4
```


#### Extract alpha channel from `.mov`

```shell
ffmpeg -i in.mov -vf alphaextract,format=yuv420p out.mp4
```

#### Compress resulting video
```shell
ffmpeg -i out.mp4 -vcodec h264 -b:v 1000k -acodec mp2 compressed_out.mp4 -y
```

#### Get first `n` frames
```shell
ffmpeg -i in.mp4 -frames:v 249 -c copy out.mp4
```

#### Cut video from `ss` till `t`
```shell
ffmpeg -ss 00:00:8.25 -i in.mp4 -t 00:00:8.25 out.mp4                                                               
```

#### Merge video with alpha channel in `.mov` file
```shell
ffmpeg -i in.mp4 -i alpha_in.mp4 -filter_complex [0][1]alphamerge -c:v qtrle out.mov
```